#RRandom script

#Random websites
website <- c("cnn.com",
             "yahoo.com",
             "google.com",
             "spotify.com",
             "bing.com",
             "aa.com",
             "apple.com",
             "netflix.com",
             "altpress.org",
             "nzfortress.co.nz",
             "evillasforsale.com",
             "playingenemy.com",
             "richardsonscharts.com",
             "xenith.net",
             "tdbrecords.com",
             "electrichumanproject.com",
             "tweekerchick.blogspot.com",
             "besound.com",
             "porkchopscreenprinting.com",
             "kinseyvisual.com",
             "rathergood.com",
             "lepoint.fr",
             "revhq.com",
             "poprocksandcoke.com",
             "samuraiblue.com",
             "openbsd.org",
             "sysblog.com",
             "voicesofsafety.com",
             "lambgoat.com",
             "paul.kedrosky.com",
             "sallyskrackers.com",
             "starmen.net",
             "casbahmusic.com",
             "bowlingshirt.com",
             "ems.org",
             "primedeep.com",
             "lovehammers.com",
             "lifehacker.com",
             "danklife.com",
             "whichisworse.com",
             "getmusic.com",
             "apple.com",
             "brunching.com",
             "loftkoeln.de",
             "monoroid.com",
             "diyordie.com",
             "you.alterFin.org",
             "atarimagazines.com",
             "reforms.net",
             "screwattack.com",
             "gaijinagogo.com",
             "yarrah.com",
             "mock.alterfin.org",
             "funxiun.com",
             "cbwgaming.com",
             "ickle.org",
             "shadowburn.com",
             "seifried.org",
             "alternet.org",
             "sbpost.ie",
             "kuro5hin.org",
             "groovechamber.com",
             "redstream.org",
             "notfoolinganybody.com",
             "southparkstudios.com",
             "guardian.co.uk",
             "securityfocus.com",
             "acidtwist.com",
             "dailyblah.com",
             "aphextwin.com",
             "streetsandavenues.com",
             "dailynews.yahoo.com",
             "xsorbit1.com",
             "watchitburn.net",
             "chapter3.net",
             "entropy8zuper.org",
             "kitchensink.org",
             "agr-s.com",
             "courrierinternational.com",
             "austrohungaro.com",
             "baseart.com",
             "sfstation.com",
             "ropm.com",
             "monsterskate.com",
             "sneakerfreak.org",
             "lowresolution.com",
             "funerisnocturnum.com",
             "rid2z.com",
             "fatfree.com",
             "bingobowden.blogspot.com",
             "nomediakings.org",
             "someonelikesme.com",
             "zetainterviu.com",
             "cs.utexas.edu",
             "enemyoftheearth.org",
             "ourbrisbane.com.au",
             "graffinc.com",
             "levenez.com",
             "darsie.net",
             "jetsetrecords.com",
             "brianmoen.com",
             "terminalfear.com",
             "empire.antville.org",
             "frykitty.com",
             "members.aol.com",
             "mitpress.mit.edu",
             "fileunder.blogspot.com",
             "sports.espn.go.com",
             "amphibiaweb.org",
             "gorenfeld.net",
             "instapundit.com",
             "meryl.net",
             "five-dollar-web-hosting.com",
             "security.nnov.ru",
             "citadeloftruth.com",
             "erkl.org",
             "testamentlegions.com",
             "unionsbuerger.de",
             "rakemag.com",
             "groupwise.bankstreet.edu",
             "igmus.org",
             "commercialbreaksandbeats.com",
             "g4techtv.com",
             "canyouseethat.com",
             "jinxworld.com",
             "wfmu.org",
             "threatmedia.com",
             "shethinks.org",
             "askeans.co.uk",
             "tao.ca",
             "nsi.org",
             "downinthevalley.com",
             "firstparish.org",
             "hcl.blogspot.com",
             "naibg.com",
             "indiarecords.com",
             "festus.com",
             "theyrule.net",
             "itv-f1.com",
             "philosophyinc.com",
             "grubb-ellis.com",
             "famousbirthdays.com",
             "mwmgraphics.com",
             "dogbomb.co.uk",
             "abstractnixon.com",
             "denverpost.com",
             "shiftydisco.co.uk",
             "freewebs.com",
             "customize.org",
             "mideastclub.com",
             "ancientfaces.com",
             "kottke.org",
             "kitsch.co.uk",
             "etc.sakasama.net",
             "jeepster.co.uk",
             "dalun.com",
             "gnu.org",
             "diariandorra.info",
             "allmusic.com",
             "screamingbloodymess.com",
             "catholicworker.org",
             "geertenbeert.nl",
             "cbel.com",
             "quickhoney.com",
             "walkerart.org",
             "killoggs.com",
             "catesgarage.com",
             "theoverprivileged.com",
             "peirce.edu",
             "anagramsite.com",
             "incompetech.com",
             "2600.com",
             "zeldaclassic.com",
             "sewwrong.com",
             "phonescoop.com",
             "nicolepangelinan.com",
             "electricdye.net",
             "chopperrecords.com",
             "soy.de",
             "soundwerkz.com",
             "seafishcamp.com",
             "newpriorities.org",
             "supersuckers.com",
             "contemporarypoetry.com",
             "yfztech.com",
             "abrahamson.ca",
             "shawnhebrank.com",
             "stevemardon.com",
             "televisionwithoutpity.com",
             "midline.net",
             "atarimagazines.com",
             "q.queso.com",
             "israblog.nana10.co.il",
             "antipodawear.com",
             "3dvelocity.com",
             "unofficial-mudhoney.com",
             "fys.kuleuven.ac.be",
             "myfootprint.org",
             "paulus.org.uk",
             "kk.org")

# Output string
output <- '"2016-09-27","07:57:22",9263737,"3.3.0","x86_64","linux-gnu","BH","1.60.0-2","DE",23657'
output <- gsub("linux-gnu",round(runif(1, 1, 25)),output) #Replace the package with a website
output <- gsub("BH",website[round(runif(1, 1, 200))],output) #Replace the package with a website
output <- gsub("07:57:22",format(Sys.time(), format = "%H:%M:%S"),output) #Repace the time with actual time
output <- gsub("23657",round(runif(1, 1, 25)),output) #Replace the package with a website
output <- gsub("9263737",round(runif(1, 1, 25)),output) #Replace the package with a website

output

# Command start
#cmdString <- paste('python send.py ', output, sep="")
cmdString <- paste('c:\\Python27\\python.exe send.py ', output, sep="")


# Send the message
system(cmdString)


